### ISSUE TITLE
AikoSExpression::scan has a buffer overrun bug, when scanning a buffer of just whitespace

### ISSUE THREAD

**Issue by geekscape** [geekscape/aiko_arduino_legacy#1]
Reported by Damien Georege ...

The problem is that if the whole string is whitespace, then the result of this function is to return a pointer equal to tail.

The bug is line 8, which could switch on a character off the end of the buffer if skipWhitespace returns tail.  The fix is to insert the following line between lines 7 and 8 in AikoSExpression.cpp

if (s >= tail) return tail;

**Comment by geekscape** [comment]
Fixed.  Suggested code added.

**Comment by geekscape** [comment]
Need to add a regression test !

**Comment by notahat** [comment]
Fixed bug in whitespace parsing. Closed by 6b2a6d6e4e48c63ba262beb2a54df3385034d27b.
